# Generated by Django 2.0.3 on 2018-09-23 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sierra', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amcproject',
            old_name='path',
            new_name='rel_path',
        ),
    ]
